### ISSUE TITLE
Unabled to upload media - TypeError: RequestInit: duplex option is required when sending a body

### ISSUE THREAD

**Issue by daedric7** [linuxserver/emulatorjs#106]
Everytime i try to upload missing media i get:

```
emulatorjs  | node:internal/deps/undici/undici:11576
emulatorjs  |     Error.captureStackTrace(err, this);
emulatorjs  |           ^
emulatorjs  | 
emulatorjs  | TypeError: RequestInit: duplex option is required when sending a body.
emulatorjs  |     at Object.fetch (node:internal/deps/undici/undici:11576:11)
emulatorjs  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
emulatorjs  | 
emulatorjs  | Node.js v18.17.1
```

How can i debug this ?

**Comment by j0nnymoe** [comment]
Post information on how you've deployed the container.

**Comment by daedric7** [comment]
> Post information on how you've deployed the container.

Apologies, it was indeed a crappy issue.

EmulatorJS deployed via docker-compose.yaml:

```
services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SUBFOLDER=/ #optional
    volumes:
      - ./config:/config
      - /share/emulatorjs/data:/data
      - /share/roms:/share/roms
    ports:
      - 3000:3000
      - 3080:80
      #- 4001:4001 #optional
    restart: unless-stopped
```

I've checked permissions on dirs, i've set everything to 777 to isolate a permission issue.

This is the file i'm trying to send, but a video causes the same problem:

![image (2)](https://github.com/linuxserver/emulatorjs/assets/4562461/d2b98868-1bbb-4d03-960c-f6de92d029f5)
