### ISSUE TITLE
No cross-browser saving

### ISSUE THREAD

**Issue by HaroldVB** [linuxserver/emulatorjs#42]
Hi,

I am experiencing an issue regarding cross-browser saving.
Whenever I play on my laptop I get my GBA and NDS save games, however when I open the emulator on my desktop I can no longer access my save states or save files. This happens every time I open a new session or open the emulator in an incognito tab.

It also displays this message when a new session is started, I have not been able to see it properly.
![image](https://user-images.githubusercontent.com/73724671/163676170-6ca80f5d-5ea1-41f4-a016-ea88cbbe37e3.png)

It seems to be making new user profiles every time.
I'm not sure if this is an issue with emulatorjs. I might have misunderstood the documentation.
Would really love to get a solution for my issue though.

Here is my docker-compose for reference.

```
version: "2.1"

volumes:
  config:

services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs
    container_name: emulatorjs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      # - SUBFOLDER=/ #optional
    volumes:
      - config:/config
      - ./data:/data
      - ./data/nds/roms:/data/nds/roms
      - ./data/gba/roms:/data/gba/roms
    ports:
      - 6749:3000
      - 6748:80
    #  - 4001:4001 #optional
    restart: unless-stopped
```
