### ISSUE TITLE
Lockscreen for webui?

### ISSUE THREAD

**Issue by r0073d-l053r** [linuxserver/emulatorjs#96]
If I want to build out my own instance of EmulatorJS using docker compose, is it safe to assume that there is an option to add a lockscreen when going to my subdomain of my instance? I would hate to build out my own instance of EmulatorJS for my own personal use and find out other people are accessing it. I couldnt find anything in the documentation, that's why I am asking here. 
Thank you kindly, r0073dl053r.

**Comment by j0nnymoe** [comment]
Use a reverse proxy and put it behind authentication.

**Comment by r0073d-l053r** [comment]
Could I do that by adding an enviroment to the compose.yml?
Such as...
"My config is built around ansible using gitlab btw."

`---
version: "2.1"
services:
  emulatorjs:
    networks:
      - nginx
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - "CUSTOM_USER={{ arcade_user }}"
      - "PASSWORD={{ arcade_password }}"
    volumes:
      - {{ docker_data }}/path/to/config:/config
      - {{ docker_data }}/path/to/data:/data
    expose:
      - 3000
      - 80
      - 4001
    restart: unless-stopped

networks:

  nginx:
    external: true
`

**Comment by r0073d-l053r** [comment]
> Use a reverse proxy and put it behind authentication.

Could I do that by adding an enviroment to the compose.yml?
Such as...
"My config is built around ansible using gitlab btw."

```yml
---
version: "2.1"
services:
  emulatorjs:
    networks:
      - nginx
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - "CUSTOM_USER={{ arcade_user }}"
      - "PASSWORD={{ arcade_password }}"
    volumes:
      - {{ docker_data }}/path/to/config:/config
      - {{ docker_data }}/path/to/data:/data
    expose:
      - 3000
      - 80
      - 4001
    restart: unless-stopped

networks:

  nginx:
    external: true
```
